// ===================================================================
// ITS Transform Kernel ROM
// Auto-generated by gen_rom_coeffs.py
// Supports DCT2(4/8/16/32/64), DCT8(4/8/16/32), DST7(4/8/16/32)
// ===================================================================

module its_rom (
    input  wire        clk,
    input  wire [13:0] addr,      // Flat address
    output reg  [15:0] coeff      // Coefficient output (signed)
);

    // ROM storage
    reg [15:0] rom [0:8175];

    // Load coefficients from hex file
    initial begin
        $readmemh("rom_coeffs.hex", rom);
    end

    // Synchronous read (1 cycle latency)
    always @(posedge clk) begin
        coeff <= rom[addr];
    end

endmodule
