// Auto-generated by gen_test_vectors.py ¡ª DO NOT EDIT
// 20 continuous TU tests (no reset between pairs)

    run_test_continuous("0000:4x4_DCT2xDCT2_lfnst0_s0", 7'd4, 7'd4, 2'd0, 2'd0, 2'd0, 2'd0,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0000_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0000_golden.hex");
    run_test_continuous("0001:4x4_DCT2xDCT2_lfnst1_s0", 7'd4, 7'd4, 2'd0, 2'd0, 2'd0, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0001_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0001_golden.hex");
    run_test_continuous("0100:8x32_DCT2xDCT2_lfnst1_s0", 7'd8, 7'd32, 2'd0, 2'd0, 2'd0, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0100_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0100_golden.hex");
    run_test_continuous("0101:8x32_DCT2xDCT2_lfnst1_s1", 7'd8, 7'd32, 2'd0, 2'd0, 2'd1, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0101_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0101_golden.hex");
    run_test_continuous("0225:4x4_DCT8xDST7_lfnst0_s0", 7'd4, 7'd4, 2'd1, 2'd2, 2'd0, 2'd0,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0225_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0225_golden.hex");
    run_test_continuous("0226:4x4_DCT8xDST7_lfnst1_s0", 7'd4, 7'd4, 2'd1, 2'd2, 2'd0, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0226_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0226_golden.hex");
    run_test_continuous("0500:4x32_DCT2xDCT8_lfnst2_s0", 7'd4, 7'd32, 2'd0, 2'd1, 2'd0, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0500_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0500_golden.hex");
    run_test_continuous("0501:4x32_DCT2xDCT8_lfnst2_s1", 7'd4, 7'd32, 2'd0, 2'd1, 2'd1, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0501_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0501_golden.hex");
    run_test_continuous("0700:32x4_DCT2xDST7_lfnst2_s2", 7'd32, 7'd4, 2'd0, 2'd2, 2'd2, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0700_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0700_golden.hex");
    run_test_continuous("0701:32x4_DCT2xDST7_lfnst2_s3", 7'd32, 7'd4, 2'd0, 2'd2, 2'd3, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0701_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0701_golden.hex");
    run_test_continuous("0900:8x32_DCT8xDCT8_lfnst0_s0", 7'd8, 7'd32, 2'd1, 2'd1, 2'd0, 2'd0,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0900_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0900_golden.hex");
    run_test_continuous("0901:8x32_DCT8xDCT8_lfnst1_s0", 7'd8, 7'd32, 2'd1, 2'd1, 2'd0, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0901_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0901_golden.hex");
    run_test_continuous("1000:16x8_DCT2xDCT8_lfnst1_s0", 7'd16, 7'd8, 2'd0, 2'd1, 2'd0, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1000_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1000_golden.hex");
    run_test_continuous("1001:16x8_DCT2xDCT8_lfnst1_s1", 7'd16, 7'd8, 2'd0, 2'd1, 2'd1, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1001_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1001_golden.hex");
    run_test_continuous("1100:16x16_DST7xDCT8_lfnst1_s1", 7'd16, 7'd16, 2'd2, 2'd1, 2'd1, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1100_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1100_golden.hex");
    run_test_continuous("1101:16x16_DST7xDCT8_lfnst1_s2", 7'd16, 7'd16, 2'd2, 2'd1, 2'd2, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1101_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1101_golden.hex");
    run_test_continuous("1300:32x16_DCT8xDCT2_lfnst1_s3", 7'd32, 7'd16, 2'd1, 2'd0, 2'd3, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1300_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1300_golden.hex");
    run_test_continuous("1301:32x16_DCT8xDCT2_lfnst2_s0", 7'd32, 7'd16, 2'd1, 2'd0, 2'd0, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1301_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1301_golden.hex");
    run_test_continuous("1375:32x32_DCT8xDCT2_lfnst2_s2", 7'd32, 7'd32, 2'd1, 2'd0, 2'd2, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1375_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1375_golden.hex");
    run_test_continuous("1376:32x32_DCT8xDCT2_lfnst2_s3", 7'd32, 7'd32, 2'd1, 2'd0, 2'd3, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1376_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1376_golden.hex");
