// Auto-generated by gen_test_vectors.py ¡ª DO NOT EDIT
// 10 end-same-cycle protocol tests

    run_test_end_same_cycle("0000:4x4_DCT2xDCT2_lfnst0_s0", 7'd4, 7'd4, 2'd0, 2'd0, 2'd0, 2'd0,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0000_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0000_golden.hex");
    run_test_end_same_cycle("0050:8x4_DCT2xDCT2_lfnst2_s0", 7'd8, 7'd4, 2'd0, 2'd0, 2'd0, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0050_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0050_golden.hex");
    run_test_end_same_cycle("0100:8x32_DCT2xDCT2_lfnst1_s0", 7'd8, 7'd32, 2'd0, 2'd0, 2'd0, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0100_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0100_golden.hex");
    run_test_end_same_cycle("0225:4x4_DCT8xDST7_lfnst0_s0", 7'd4, 7'd4, 2'd1, 2'd2, 2'd0, 2'd0,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0225_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0225_golden.hex");
    run_test_end_same_cycle("0400:4x16_DCT8xDCT8_lfnst1_s3", 7'd4, 7'd16, 2'd1, 2'd1, 2'd3, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0400_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0400_golden.hex");
    run_test_end_same_cycle("0600:16x4_DST7xDCT8_lfnst2_s1", 7'd16, 7'd4, 2'd2, 2'd1, 2'd1, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0600_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0600_golden.hex");
    run_test_end_same_cycle("0800:8x8_DCT8xDCT2_lfnst2_s3", 7'd8, 7'd8, 2'd1, 2'd0, 2'd3, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_0800_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_0800_golden.hex");
    run_test_end_same_cycle("1000:16x8_DCT2xDCT8_lfnst1_s0", 7'd16, 7'd8, 2'd0, 2'd1, 2'd0, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1000_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1000_golden.hex");
    run_test_end_same_cycle("1200:16x32_DCT2xDST7_lfnst1_s2", 7'd16, 7'd32, 2'd0, 2'd2, 2'd2, 2'd1,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1200_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1200_golden.hex");
    run_test_end_same_cycle("1376:32x32_DCT8xDCT2_lfnst2_s3", 7'd32, 7'd32, 2'd1, 2'd0, 2'd3, 2'd2,
             "D:/Workspace/its_vvc/tb/test_vectors/case_1376_input.hex",
             "D:/Workspace/its_vvc/tb/test_vectors/case_1376_golden.hex");
